project:
  type: website
  output-dir: docs

website:
  title: "Load Time Test"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Python"
        contents: 
          - Python_Shinylive_1.qmd
          - Python_Shinylive_2.qmd
      - section: "R base"
        contents: 
          - R_Shinylive_1.qmd
          - R_Shinylive_2.qmd
      - section: "R libs"
        contents: 
          - R_lib_Shinylive_1.qmd
          - R_lib_Shinylive_2.qmd

format:
  html:
    theme: cosmo
    toc: true
    
filters:
  - shinylive    